In [5]:
#판다스 설치
!pip install pandas

Requirement already satisfied: pandas in c:\users\krcea\appdata\local\programs\python\python314\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\krcea\appdata\local\programs\python\python314\lib\site-packages (from pandas) (2.4.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\krcea\appdata\roaming\python\python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\krcea\appdata\local\programs\python\python314\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\krcea\appdata\local\programs\python\python314\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\krcea\appdata\roaming\python\python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [4]:
import pandas

In [6]:
#시리즈(Series)

menu = pandas. Series(["비빔밥", "김치찌개", "된장찌개"])
menu

0     비빔밥
1    김치찌개
2    된장찌개
dtype: object

In [7]:
type(menu)

pandas.core.series.Series

In [10]:
price = pandas.Series([1000,2000,3000])
price

0    1000
1    2000
2    3000
dtype: int64

In [14]:
# 데이터프레임(DataFrame)

import pandas as pd

df = pd.DataFrame( {
    "메뉴": menu,
    "가격": price
})

df

     메뉴    가격
0   비빔밥  1000
1  김치찌개  2000
2  된장찌개  3000

In [16]:
df = pd.DataFrame({
    "메뉴": ["비빔밥", "김치찌개", "된장찌개"],
    "가격": [10000, 9000, 8000],
    "원산지": ["한국", "한국", "한국"] 
})

df

     메뉴     가격 원산지
0   비빔밥  10000  한국
1  김치찌개   9000  한국
2  된장찌개   8000  한국

In [ ]:
#컬럼 선택
df["메뉴"]
df["가격"]

0    10000
1     9000
2     8000
Name: 가격, dtype: int64

In [22]:

df[["메뉴","가격"]]

     메뉴     가격
0   비빔밥  10000
1  김치찌개   9000
2  된장찌개   8000

In [25]:
# 02. 데이터 저장 및 불러오기

data = {
    "메뉴": ["아메리카노", "카페라떼", "카페모카", " 카푸치노", "에스프레소", "밀크티", "녹차"],
    "가격": ["4500", "5000", "3000", " 7000", "500", "300", "1000"],
    "칼로리": ["450", "50", "30", " 70", "5", "3", "100"],
}

df = pd.DataFrame(data)
df

      메뉴     가격  칼로리
0  아메리카노   4500  450
1   카페라떼   5000   50
2   카페모카   3000   30
3   카푸치노   7000   70
4  에스프레소    500    5
5    밀크티    300    3
6     녹차   1000  100

In [29]:

# csv 파일로 저장
df.to_csv("temp.csv", index=False)

In [30]:
# csv 파일로 불러오기

pd.read_csv("temp.csv")

      메뉴    가격  칼로리
0  아메리카노  4500  450
1   카페라떼  5000   50
2   카페모카  3000   30
3   카푸치노  7000   70
4  에스프레소   500    5
5    밀크티   300    3
6     녹차  1000  100

In [34]:
#03. 탐색적 데이터 분석(EDA)

df = pd.read_csv("temp.csv")

df.head()  ## head: 상위 5개 행만 불러옴
df.head(2) ## 상위 n개만 불러옴

df.tail() ## tail : 하위 5개 행 불러옴
df.tail(3) ## tail : 하위 n개 행 불러옴

      메뉴    가격  칼로리
4  에스프레소   500    5
5    밀크티   300    3
6     녹차  1000  100

In [ ]:
#데이터 프레임의 크기 (행,열)

df. shape

(7, 3)

In [36]:
# 컬럼별 자료형
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   메뉴      7 non-null      object
 1   가격      7 non-null      int64
 2   칼로리     7 non-null      int64
dtypes: int64(2), object(1)
memory usage: 300.0+ bytes

In [37]:
# 상관관계
df.corr(numeric_only=True)

           가격       칼로리
가격   1.000000  0.330027
칼로리  0.330027  1.000000

In [42]:
# 고유한 값의 개수

data = {
    "car": ["Sedan", "SUV", "Sedan", "SUV", "SUV", "Sedan", "Sedan", "Sedan", "Sedan", "SUV"],
    "size": ["S","M", "M", "S", "L", "S", "L", "M","M", "L" ]
}

df_car = pd.DataFrame(data)
df_car.head(3)

df_car.nunique()

car     2
size    3
dtype: int64

In [46]:
df_car.value_counts()
print(df_car["car"].value_counts())
print(df_car["size"].value_counts())

car
Sedan    6
SUV      4
Name: count, dtype: int64
size
M    4
S    3
L    3
Name: count, dtype: int64

In [47]:
#기술통계

df_car.describe()

          car size
count      10   10
unique      2    3
top     Sedan    M
freq        6    4

In [49]:
df.describe()
df

      메뉴    가격  칼로리
0  아메리카노  4500  450
1   카페라떼  5000   50
2   카페모카  3000   30
3   카푸치노  7000   70
4  에스프레소   500    5
5    밀크티   300    3
6     녹차  1000  100

In [50]:
# 기술통계(object 자료형)

df.describe(include="object")

           메뉴
count       7
unique      7
top     아메리카노
freq        1

In [54]:
# 4. 자료형 변환

data = {
    "메뉴": ["아메리카노", "카페라떼", "카페모카", " 카푸치노", "에스프레소", "밀크티", "녹차"],
    "가격": [4500.0, 5000.0, 3000.0, 7000.0, 500.0, 300.0, 1000.0],
    "칼로리": [450.0, 50.0, 30.0, 70.0, 5.0, 3.0, 100.0],
}
df = pd.DataFrame(data)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   메뉴      7 non-null      object
 1   가격      7 non-null      float64
 2   칼로리     7 non-null      float64
dtypes: float64(2), object(1)
memory usage: 300.0+ bytes

In [58]:
df["가격"] = df["가격"].astype(int)

In [59]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   메뉴      7 non-null      object
 1   가격      7 non-null      int64
 2   칼로리     7 non-null      float64
dtypes: float64(1), int64(1), object(1)
memory usage: 300.0+ bytes

In [60]:
df["가격"] = df["가격"].astype(float)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   메뉴      7 non-null      object
 1   가격      7 non-null      float64
 2   칼로리     7 non-null      float64
dtypes: float64(2), object(1)
memory usage: 300.0+ bytes

In [61]:
#5. 새로운 컬럼 추가

df = pd. read_csv("temp.csv")
df.head(2)

      메뉴    가격  칼로리
0  아메리카노  4500  450
1   카페라떼  5000   50

In [62]:
df["new"] = 0
df

      메뉴    가격  칼로리  new
0  아메리카노  4500  450    0
1   카페라떼  5000   50    0
2   카페모카  3000   30    0
3   카푸치노  7000   70    0
4  에스프레소   500    5    0
5    밀크티   300    3    0
6     녹차  1000  100    0

In [63]:
#기존 컬럼을 사용한 계산
discount = 0.2
df["할인가"] = df["가격"] * (1-discount)
df

      메뉴    가격  칼로리  new     할인가
0  아메리카노  4500  450    0  3600.0
1   카페라떼  5000   50    0  4000.0
2   카페모카  3000   30    0  2400.0
3   카푸치노  7000   70    0  5600.0
4  에스프레소   500    5    0   400.0
5    밀크티   300    3    0   240.0
6     녹차  1000  100    0   800.0

In [66]:
# 6. 데이터 삭제

df = pd.read_csv("temp.csv")
df

      메뉴    가격  칼로리
0  아메리카노  4500  450
1   카페라떼  5000   50
2   카페모카  3000   30
3   카푸치노  7000   70
4  에스프레소   500    5
5    밀크티   300    3
6     녹차  1000  100

In [71]:
# 행 삭제
df = df.drop(1, axis=0)

KeyError: '[1] not found in axis'

In [75]:
df = df.drop(5,axis=0, inplace=True)

KeyError: '[5] not found in axis'

In [74]:
df

      메뉴    가격  칼로리
0  아메리카노  4500  450
2   카페모카  3000   30
3   카푸치노  7000   70
4  에스프레소   500    5
6     녹차  1000  100

In [76]:
#컬럼(열) 삭제

df = df.drop("칼로리", axis = 1)

In [77]:
df

      메뉴    가격
0  아메리카노  4500
2   카페모카  3000
3   카푸치노  7000
4  에스프레소   500
6     녹차  1000